topics/runOnly-relevantTests-during-deployment/main/default/objects/Opportunity/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <label>Discount</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

topics/runOnly-relevantTests-during-deployment/main/default/objects/Opportunity/fields/Manager_Approved__c.field-meta.xml
<CustomField>
    <fullName>Manager_Approved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Manager Approved</label>
    <type>Checkbox</type>
</CustomField>

topics/runOnly-relevantTests-during-deployment/main/default/classes/OpportunityDiscountService.cls
public class OpportunityDiscountService {
    public static void enforceApproval(List<Opportunity> newList, Map<Id, Opportunity> oldMap) {
        for (Opportunity opp : newList) {
            // Only enforce when Discount__c changes (or on insert)
            Decimal newDiscount = opp.Discount__c;
            Decimal oldDiscount = (oldMap != null && oldMap.containsKey(opp.Id)) ? oldMap.get(opp.Id).Discount__c : null;

            Boolean discountChanged = (oldMap == null) || (newDiscount != oldDiscount);
            /*if (oldMap == null) {
                opp.Type = 'New Customer';
            }*/
            
            if (!discountChanged) {
                continue;
            }

            if (newDiscount != null && newDiscount > 40 && opp.Manager_Approved__c != true) {
                opp.addError('Discounts over 40% require manager approval.');
            }
        }
    }

    public static void test3(List<Opportunity> newList, Map<Id, Opportunity> oldMap) {
        for (Opportunity opp : newList) {
           
            if (oldMap == null) {
                opp.Type = 'New Customer';
            }
        }
    }
}